const SUBJECTS = [
  { id: 'literature', name: '文学', glyph: '文', color: '#d97a62' },
  { id: 'sociology', name: '社会学', glyph: '社', color: '#8aa899' },
  { id: 'politics', name: '政治学', glyph: '政', color: '#c3a261' },
  { id: 'history', name: '历史学', glyph: '史', color: '#7f9fc1' },
  { id: 'philosophy', name: '哲学', glyph: '哲', color: '#9a86b8' },
  { id: 'law', name: '法学', glyph: '法', color: '#b7846e' },
]

const PAIRS = [
  { id:'lit-1', subject:'literature', era:'ancient', china:{year:-1050,title:'《诗经》传统形成',person:'先秦诗人群体',text:'风、雅、颂把礼乐秩序、地方生活与个人情感放进共同的声音。'}, world:{year:-750,title:'荷马史诗定型',person:'荷马传统',text:'《伊利亚特》《奥德赛》以英雄、战争和归乡组织希腊世界的共同记忆。'}, question:'口传诗歌如何成为一个文明认识自己的方式？' },
  { id:'lit-2', subject:'literature', era:'ancient', china:{year:100,title:'《楚辞》编定与流传',person:'屈原传统、王逸',text:'“骚体”让个人身世、政治理想与神话想象进入汉语抒情传统。'}, world:{year:8,title:'《变形记》完成',person:'奥维德',text:'以连续变形故事重述希腊罗马神话，讨论欲望、权力与身份。'}, question:'神话进入文学后，个人命运如何与政治秩序纠缠？' },
  { id:'lit-3', subject:'literature', era:'medieval', china:{year:760,title:'盛唐诗歌高峰',person:'李白、杜甫、王维',text:'个人经验、战争现实与山水世界共同拓展了古典诗歌的尺度。'}, world:{year:800,title:'《贝奥武夫》手稿传统',person:'盎格鲁-撒克逊诗人',text:'英雄史诗在基督教书写与日耳曼口传传统之间保存旧世界。'}, question:'诗歌怎样同时容纳个人声音与共同体记忆？' },
  { id:'lit-4', subject:'literature', era:'medieval', china:{year:1300,title:'元杂剧繁盛',person:'关汉卿、王实甫',text:'城市演出、角色行当与曲词结合，使舞台成为观察日常伦理的公共空间。'}, world:{year:1321,title:'《神曲》完成',person:'但丁',text:'以地狱、炼狱、天堂的旅程整合神学宇宙、政治判断与个人爱。'}, question:'文学如何借虚构空间审判现实社会？' },
  { id:'lit-5', subject:'literature', era:'modern', china:{year:1791,title:'《红楼梦》程甲本刊行',person:'曹雪芹、高鹗、程伟元',text:'家族兴衰、女性群像与日常生活共同构成对盛世内部裂缝的凝视。'}, world:{year:1813,title:'《傲慢与偏见》出版',person:'简·奥斯汀',text:'婚姻、财产与判断力在乡绅社会的日常交往中展开。'}, question:'家庭与婚姻叙事如何显影阶层、财产和性别秩序？' },
  { id:'lit-6', subject:'literature', era:'modern', china:{year:1918,title:'《狂人日记》发表',person:'鲁迅',text:'白话小说借“狂人”的眼睛重审礼教、历史与现代主体。'}, world:{year:1922,title:'《尤利西斯》出版',person:'詹姆斯·乔伊斯',text:'把一天的城市漫游写成意识、语言和现代生活的百科全书。'}, question:'现代文学为什么要打碎旧的叙述语言？' },

  { id:'soc-1', subject:'sociology', era:'ancient', china:{year:-300,title:'“群”与礼的社会思想',person:'荀子',text:'从人的欲望、分工与礼义出发解释群体秩序何以可能。'}, world:{year:-350,title:'城邦与人的社会性',person:'亚里士多德',text:'《政治学》把人理解为在城邦共同生活中实现自身的动物。'}, question:'社会秩序来自自然倾向、制度教化，还是二者的结合？' },
  { id:'soc-2', subject:'sociology', era:'medieval', china:{year:1170,title:'宗族礼制的系统化',person:'朱熹及宋代理学家',text:'家礼、宗族与地方社会实践，把伦理秩序落实到日常关系。'}, world:{year:1377,title:'《历史绪论》写成',person:'伊本·赫勒敦',text:'以群体团结、城市与王朝循环解释社会和政治变迁。'}, question:'家庭伦理与群体团结，如何支撑更大规模的政治秩序？' },
  { id:'soc-3', subject:'sociology', era:'modern', china:{year:1903,title:'《群学肄言》刊行',person:'严复',text:'译述斯宾塞社会学，把“群学”引入晚清改革与救亡讨论。'}, world:{year:1895,title:'《社会学方法的准则》出版',person:'涂尔干',text:'提出把社会事实当作“物”来研究，确立学科方法自觉。'}, question:'社会学进入大学之前，先回应了怎样的国家与秩序危机？' },
  { id:'soc-4', subject:'sociology', era:'contemporary', china:{year:1947,title:'《乡土中国》出版',person:'费孝通',text:'以差序格局、礼治秩序等概念理解中国基层社会结构。'}, world:{year:1959,title:'《社会学的想象力》出版',person:'C. 赖特·米尔斯',text:'把个人困扰连接到公共议题与历史结构。'}, question:'怎样从日常经验出发，看见个人背后的社会结构？' },
  { id:'soc-5', subject:'sociology', era:'contemporary', china:{year:1980,title:'中国社会学恢复重建',person:'费孝通等学者',text:'学科建制、社会调查与本土化问题重新进入大学和公共研究。'}, world:{year:1984,title:'《区分》英译传播',person:'皮埃尔·布迪厄',text:'趣味、文化资本与阶层再生产成为文化社会学的重要框架。'}, question:'学科重建与阶层文化研究，如何回应快速变化的社会？' },

  { id:'pol-1', subject:'politics', era:'ancient', china:{year:-356,title:'商鞅第一次变法',person:'商鞅、秦孝公',text:'以县制、军功与法律重塑国家汲取能力和社会身份。'}, world:{year:-375,title:'《理想国》思想形成',person:'柏拉图',text:'通过正义、教育与哲人王追问好城邦的构造。'}, question:'强国家与正义国家，是同一个问题吗？' },
  { id:'pol-2', subject:'politics', era:'ancient', china:{year:-221,title:'秦完成政治统一',person:'秦始皇及秦官僚体系',text:'郡县、文书与标准化把多地域纳入统一帝国治理。'}, world:{year:-27,title:'罗马元首制确立',person:'奥古斯都',text:'共和制度形式与个人最高权力结合，开启罗马帝国秩序。'}, question:'帝国如何在广阔地域中同时制造统一与合法性？' },
  { id:'pol-3', subject:'politics', era:'early-modern', china:{year:1669,title:'《黄宗羲定本》思想流传',person:'黄宗羲',text:'《明夷待访录》反思君主专制、学校与公共议论。'}, world:{year:1689,title:'《政府论》出版',person:'约翰·洛克',text:'以自然权利、同意与反抗权论证有限政府。'}, question:'面对君主权力，中西思想分别从哪里寻找约束？' },
  { id:'pol-4', subject:'politics', era:'modern', china:{year:1902,title:'“新民”政治论述展开',person:'梁启超',text:'把国民、公德与政治参与放进国家转型的核心。'}, world:{year:1919,title:'《政治作为一种志业》演讲',person:'马克斯·韦伯',text:'讨论国家、正当暴力、责任伦理与政治家的判断。'}, question:'现代政治需要怎样的国民，又需要怎样的政治家？' },
  { id:'pol-5', subject:'politics', era:'contemporary', china:{year:1982,title:'现行宪法通过',person:'第五届全国人民代表大会',text:'确立改革时期国家机构、公民权利与根本制度的宪法框架。'}, world:{year:1971,title:'《正义论》出版',person:'约翰·罗尔斯',text:'以原初状态和差别原则重构自由民主社会的公平问题。'}, question:'制度文本中的权利，与规范理论中的正义如何互相检验？' },

  { id:'his-1', subject:'history', era:'ancient', china:{year:-91,title:'《史记》基本完成',person:'司马迁',text:'纪传体连接帝王、世家与个人命运，追问天人之际与古今之变。'}, world:{year:-430,title:'《历史》写作',person:'希罗多德',text:'以战争、旅行见闻与多民族叙事探寻希波冲突的原因。'}, question:'历史写作如何在事实记录、见闻与道德判断之间取舍？' },
  { id:'his-2', subject:'history', era:'medieval', china:{year:1084,title:'《资治通鉴》完成',person:'司马光及编修团队',text:'编年叙事以历代兴衰为统治者提供政治鉴戒。'}, world:{year:731,title:'《英吉利教会史》完成',person:'比德',text:'把英格兰诸族的历史放入基督教传播与统一叙事。'}, question:'“以史为鉴”和“以史立国”分别怎样选择材料？' },
  { id:'his-3', subject:'history', era:'early-modern', china:{year:1640,title:'《读通鉴论》思想酝酿',person:'王夫之',text:'借历代政治得失反思明亡，并强调历史处境中的变化与责任。'}, world:{year:1681,title:'《历史批判辞典》前夜',person:'皮埃尔·贝尔等早期批判史家',text:'文本辨伪、宗教争论与怀疑精神推动近代史学批判。'}, question:'王朝覆亡与宗教冲突如何迫使史家重写因果？' },
  { id:'his-4', subject:'history', era:'modern', china:{year:1902,title:'《新史学》发表',person:'梁启超',text:'批评帝王中心旧史，主张书写国民、群体与进化。'}, world:{year:1902,title:'《历史研究》相关讲座时代',person:'阿克顿等职业史家',text:'档案、专业训练与客观性理想塑造现代大学史学。'}, question:'现代史学为何同时转向“人民”与“专业”？' },
  { id:'his-5', subject:'history', era:'contemporary', china:{year:1949,title:'中国马克思主义史学体系化',person:'郭沫若、范文澜等',text:'社会形态、阶级与人民成为解释中国历史的重要框架。'}, world:{year:1949,title:'《地中海》出版',person:'费尔南·布罗代尔',text:'长时段、地理结构与物质生活改变了事件中心史学。'}, question:'宏大结构能解释多少历史，又会遮蔽哪些人的经验？' },

  { id:'phi-1', subject:'philosophy', era:'ancient', china:{year:-480,title:'孔子言说结集的时代',person:'孔子及其弟子',text:'从仁、礼、学习与君子实践讨论人成为人的路径。'}, world:{year:-399,title:'苏格拉底之死',person:'苏格拉底、柏拉图',text:'以诘问、德性与未经省察的生活奠定西方伦理哲学场景。'}, question:'哲学首先是一套理论，还是一种自我修养的生活？' },
  { id:'phi-2', subject:'philosophy', era:'ancient', china:{year:-300,title:'庄子思想形成',person:'庄周及后学',text:'以寓言、齐物与逍遥松动固定的是非、身份和知识边界。'}, world:{year:-300,title:'斯多亚学派兴起',person:'芝诺及其后学',text:'在不可控世界中，以理性、德性与情绪训练寻求自由。'}, question:'当外部世界不可控，人如何获得内在自由？' },
  { id:'phi-3', subject:'philosophy', era:'medieval', china:{year:1177,title:'朱熹编定《四书章句集注》',person:'朱熹',text:'以理、气、格物与修养重构儒学知识和教育体系。'}, world:{year:1274,title:'《神学大全》未竟',person:'托马斯·阿奎那',text:'系统协调亚里士多德哲学、基督教神学与自然法。'}, question:'经典注释如何变成一整套关于世界与人的体系？' },
  { id:'phi-4', subject:'philosophy', era:'early-modern', china:{year:1527,title:'王阳明讲学与心学成熟',person:'王阳明',text:'知行合一与致良知把道德判断落实到主体行动。'}, world:{year:1637,title:'《谈谈方法》出版',person:'勒内·笛卡尔',text:'从方法怀疑和“我思”出发，为知识寻找确定基础。'}, question:'可靠知识来自道德直觉、实践行动，还是方法怀疑？' },
  { id:'phi-5', subject:'philosophy', era:'modern', china:{year:1919,title:'杜威访华与实用主义传播',person:'杜威、胡适等',text:'实验主义、教育改革与问题意识进入新文化讨论。'}, world:{year:1921,title:'《逻辑哲学论》出版',person:'维特根斯坦',text:'以语言、逻辑与世界的界限重新界定哲学工作。'}, question:'哲学应当解决现实问题，还是澄清语言能够说什么？' },

  { id:'law-1', subject:'law', era:'ancient', china:{year:-536,title:'子产铸刑书',person:'子产',text:'将刑法条文公布于众，引发成文法与礼治关系的争论。'}, world:{year:-450,title:'《十二表法》公布',person:'罗马共和国',text:'以公开成文规则回应平民对贵族司法垄断的不满。'}, question:'法律被公开写下，如何改变权力与普通人的关系？' },
  { id:'law-2', subject:'law', era:'medieval', china:{year:653,title:'《永徽律疏》颁行',person:'唐高宗时期律学家',text:'律文与官方疏议结合，系统表达礼法关系与帝国司法秩序。'}, world:{year:534,title:'《查士丁尼法典》体系完成',person:'查士丁尼一世及法学家',text:'汇编罗马皇帝敕令、法学著作与制度，深刻影响欧陆法传统。'}, question:'大型帝国为什么都需要整理、解释并统一既有法律？' },
  { id:'law-3', subject:'law', era:'early-modern', china:{year:1646,title:'《大清律集解附例》颁行',person:'清初修律官员',text:'继承明律框架并结合条例，奠定清代基本法典秩序。'}, world:{year:1689,title:'英国《权利法案》通过',person:'英国议会',text:'限制王权并确认议会与臣民若干权利，重塑宪制关系。'}, question:'法典化秩序与宪制限权，代表两种不同的法律任务吗？' },
  { id:'law-4', subject:'law', era:'modern', china:{year:1902,title:'晚清修律启动',person:'沈家本、伍廷芳等',text:'在主权危机与领事裁判权压力下，系统引入近代部门法。'}, world:{year:1900,title:'《德国民法典》施行',person:'德国法学界与帝国立法机关',text:'以高度体系化的总则与部门结构影响多国民法编纂。'}, question:'法律移植如何在现代化需求与本土秩序之间发生？' },
  { id:'law-5', subject:'law', era:'contemporary', china:{year:1954,title:'中华人民共和国宪法通过',person:'第一届全国人民代表大会',text:'规定国家结构、根本制度与公民基本权利义务。'}, world:{year:1950,title:'《欧洲人权公约》签署',person:'欧洲委员会成员国',text:'建立区域人权保障框架，并发展出跨国司法监督。'}, question:'二战后的宪法与人权文件，如何重新定义国家权力边界？' },
  { id:'law-6', subject:'law', era:'contemporary', china:{year:2020,title:'《中华人民共和国民法典》通过',person:'第十三届全国人民代表大会',text:'整合民事单行法，以七编体系规定民事主体、权利与交易生活。'}, world:{year:2018,title:'欧盟《通用数据保护条例》实施',person:'欧盟',text:'以数据主体权利、问责与域外适用回应数字社会的隐私问题。'}, question:'数字时代，传统民事权利如何扩展到人格与数据？' },
]

const BOOKS = [
  {id:'b01',subject:'literature',region:'china',title:'诗经',author:'佚名',year:'先秦',level:'基础',note:'先读《国风》：观察情感如何被礼仪、劳动与地方声音承载。'},
  {id:'b02',subject:'literature',region:'china',title:'红楼梦',author:'曹雪芹',year:'18世纪',level:'核心',note:'不要只追情节；给人物的财产、身份与情感关系做一张图。'},
  {id:'b03',subject:'literature',region:'world',title:'奥德赛',author:'荷马',year:'约前8世纪',level:'基础',note:'把“归乡”当作身份重建，而不只是冒险故事。'},
  {id:'b04',subject:'literature',region:'world',title:'傲慢与偏见',author:'简·奥斯汀',year:'1813',level:'基础',note:'记录每次误判背后的阶层信息与财产规则。'},
  {id:'b05',subject:'sociology',region:'china',title:'乡土中国',author:'费孝通',year:'1947',level:'基础',note:'每读一个概念，都为它找一个当代生活中的反例。'},
  {id:'b06',subject:'sociology',region:'china',title:'金翼',author:'林耀华',year:'1944',level:'进阶',note:'把家族故事当作社会结构的切片来读。'},
  {id:'b07',subject:'sociology',region:'world',title:'社会学的想象力',author:'C. 赖特·米尔斯',year:'1959',level:'基础',note:'试着把一个个人困扰改写成公共议题。'},
  {id:'b08',subject:'sociology',region:'world',title:'自杀论',author:'埃米尔·涂尔干',year:'1897',level:'进阶',note:'重点看作者如何把道德议题变成可检验的社会问题。'},
  {id:'b09',subject:'politics',region:'china',title:'商君书',author:'商鞅学派',year:'战国',level:'进阶',note:'区分“国家能力”“君主权力”与“社会代价”。'},
  {id:'b10',subject:'politics',region:'china',title:'明夷待访录',author:'黄宗羲',year:'1663',level:'核心',note:'比较“天下之法”与“一家之法”的论证起点。'},
  {id:'b11',subject:'politics',region:'world',title:'政治学',author:'亚里士多德',year:'前4世纪',level:'核心',note:'先弄清城邦、公民与好生活之间的关系。'},
  {id:'b12',subject:'politics',region:'world',title:'政治作为一种志业',author:'马克斯·韦伯',year:'1919',level:'基础',note:'用现实例子区分信念伦理与责任伦理。'},
  {id:'b13',subject:'history',region:'china',title:'史记',author:'司马迁',year:'前1世纪',level:'核心',note:'选同一事件的本纪与列传对读，观察叙事视角。'},
  {id:'b14',subject:'history',region:'china',title:'万历十五年',author:'黄仁宇',year:'1981',level:'基础',note:'注意“小事件”怎样暴露制度无法运转的结构。'},
  {id:'b15',subject:'history',region:'world',title:'历史',author:'希罗多德',year:'前5世纪',level:'核心',note:'标记作者的亲见、转述和推测，比较证据层级。'},
  {id:'b16',subject:'history',region:'world',title:'历史的用途与滥用',author:'尼采',year:'1874',level:'进阶',note:'问自己：哪一种历史正在帮助生活，哪一种在压迫生活？'},
  {id:'b17',subject:'philosophy',region:'china',title:'论语',author:'孔子弟子及再传弟子',year:'战国前期',level:'基础',note:'按“学习、关系、政治、修养”重排章句，而非逐篇读完。'},
  {id:'b18',subject:'philosophy',region:'china',title:'庄子',author:'庄周及后学',year:'战国',level:'核心',note:'把寓言视为思想实验，观察它如何瓦解固定立场。'},
  {id:'b19',subject:'philosophy',region:'world',title:'苏格拉底的申辩',author:'柏拉图',year:'前4世纪',level:'基础',note:'追踪苏格拉底为何把“不知道”变成一种力量。'},
  {id:'b20',subject:'philosophy',region:'world',title:'谈谈方法',author:'勒内·笛卡尔',year:'1637',level:'基础',note:'区分作者实际使用的方法与后来被概括的“我思”。'},
  {id:'b21',subject:'law',region:'china',title:'唐律疏议',author:'长孙无忌等',year:'653',level:'进阶',note:'从一个具体罪名看礼、身份与刑罚如何连接。'},
  {id:'b22',subject:'law',region:'china',title:'中国法律与中国社会',author:'瞿同祖',year:'1947',level:'核心',note:'把家族、阶级与法律条文放在同一分析框架中。'},
  {id:'b23',subject:'law',region:'world',title:'法律的概念',author:'H. L. A. 哈特',year:'1961',level:'进阶',note:'先掌握初级规则、次级规则和承认规则三个支点。'},
  {id:'b24',subject:'law',region:'world',title:'论法的精神',author:'孟德斯鸠',year:'1748',level:'核心',note:'不要只读“三权分立”；看法律如何受地理、风俗和政体制约。'},
]

const ERA_STORIES = [
  {id:'ancient',range:'公元前 800—公元 500',name:'古典奠基',kicker:'城市、礼制与帝国',context:'农业共同体扩张为城邦与帝国，口传经验逐渐被经典、史书和成文法固定下来。知识尚未分科，诗、史、哲与政治共享“何为好秩序”的问题。',style:'格言、对话、寓言、史诗与纪传成为主要表达；重记忆、典范和公共劝说。',shift:'从神话记忆走向理性论辩与制度书写'},
  {id:'medieval',range:'500—1500',name:'信仰与体系',kicker:'经典注释、宗教世界与官僚国家',context:'跨地域宗教、帝国官僚和士人教育塑造知识生产。作者常通过注经、编史和法典整理，把分散传统组织成可传授的体系。',style:'注疏、编年、神学论证与象征叙事发达；文体追求秩序、层级与整体宇宙观。',shift:'从奠定经典走向解释经典、整合世界'},
  {id:'early-modern',range:'1500—1800',name:'主体觉醒',kicker:'印刷、商业扩张与国家重组',context:'印刷传播、海洋扩张、宗教冲突和集权国家带来新的读者与公共讨论。个人经验、权利与方法开始成为独立问题。',style:'章回小说、随笔、政治论说与方法论文兴盛；经验细节和论证结构都更鲜明。',shift:'从共同信仰走向主体、经验与权利'},
  {id:'modern',range:'1800—1945',name:'现代裂变',kicker:'工业、民族国家与大众社会',context:'工业化、殖民体系、民族国家和城市生活重塑社会。六门学科陆续专业化，同时文学以新语言回应断裂、异化和革命。',style:'现实主义、白话、意识流、统计调查与专业论文并行；旧体裁被拆解，作者主动发明新读者。',shift:'从通人之学走向分科知识与大众公共领域'},
  {id:'contemporary',range:'1945—至今',name:'结构与多元',kicker:'战后秩序、去殖民与数字社会',context:'战后制度、去殖民、全球化与数字技术让权利、身份、结构和日常生活成为共同焦点。知识更加跨学科，也更警惕单一宏大叙事。',style:'概念模型、微观叙事、跨媒介写作和数据研究共存；强调位置、证据与多重声音。',shift:'从单线进步走向结构分析、差异经验与全球关联'}
]

const AUTHORS = [
  {id:'quyuan',subject:'literature',region:'china',year:-300,dates:'约前 340—前 278',name:'屈原',alias:'骚体传统的奠基者',era:'ancient',period:'战国 · 楚国',summary:'把政治失意、人格理想与神话想象熔为强烈的第一人称抒情，使“我”的命运第一次如此醒目地进入汉语诗歌。',life:'出身楚国贵族，曾参与政务，后在政治斗争中被疏远、流放。其生平记载与作品归属均有争议，但“屈原”作为忠贞诗人的文化形象影响深远。',context:'诸侯竞争与楚地巫风交叠，士人开始以个人才性面对国家命运。',style:['香草美人式象征','铺陈、反复与诘问','神游结构和瑰丽意象'],ideas:['个人操守与政治共同体','忠贞、放逐与自我证明'],works:[{title:'离骚',year:'战国',intro:'以长篇自叙、求索和神游书写理想人格无法见容于现实政治的悲剧。'},{title:'九歌',year:'战国',intro:'借楚地祭歌与人神相遇，形成缠绵、幽微又富仪式感的抒情世界。'}],links:[['libai','浪漫抒情传统']]},
  {id:'libai',subject:'literature',region:'china',year:740,dates:'701—762',name:'李白',alias:'盛唐浪漫诗歌高峰',era:'medieval',period:'唐 · 盛唐',summary:'把游历、饮酒、友情、政治抱负和宇宙想象写成高度流动的诗歌，让个体精神获得近乎神话般的尺度。',life:'早年游历蜀中，长期漫游求仕；曾入长安供奉翰林，后离京。安史之乱中卷入永王事件并获罪，晚年漂泊。',context:'帝国开放、交通扩张与士人入仕理想并存，盛世气象背后已有政治危机。',style:['跳跃夸张的想象','口语般自然的节奏','古体与乐府的自由伸展'],ideas:['自由人格与功业焦虑','人在山水宇宙中的位置'],works:[{title:'将进酒',year:'约 752',intro:'以奔涌节奏把生命短暂、怀才不遇与豪饮放在同一场情绪爆发中。'},{title:'蜀道难',year:'盛唐',intro:'用神话、夸张和声音层次，把道路写成自然奇观与政治寓言。'}],links:[['quyuan','承接骚体想象'],['luxun','古典语言与现代断裂']]},
  {id:'caoxueqin',subject:'literature',region:'china',year:1750,dates:'约 1715—1763',name:'曹雪芹',alias:'世情小说的集大成者',era:'early-modern',period:'清 · 乾隆前期',summary:'以家族日常、女性群像和诗性细节写出盛世内部的衰败机制，把个人情感与制度性命运交织成复杂世界。',life:'出身江宁织造曹氏家族，少年经历家族由盛转衰，后居北京西郊，生活困顿。《红楼梦》前八十回通常被认为出自其手。',context:'商品经济与文人文化繁荣，宗法家族、科举和财产制度仍支配个人道路。',style:['多声部人物视角','日常细节中的伏笔','诗词、戏曲与小说互文'],ideas:['情与礼法的冲突','繁华必然消逝的历史感'],works:[{title:'红楼梦',year:'18 世纪中叶',intro:'以贾府兴衰和宝黛爱情为中心，展开关于家族、性别、欲望与幻灭的百科全书式叙事。'}],links:[['luxun','现代小说批评的前史']]},
  {id:'luxun',subject:'literature',region:'china',year:1918,dates:'1881—1936',name:'鲁迅',alias:'中国现代文学的开路者',era:'modern',period:'晚清—民国',summary:'用冷峻反讽、象征和杂文解剖旧伦理如何进入人的精神内部，并逼迫现代汉语承担自我批判。',life:'生于绍兴，早年赴日学医后转向文学。回国后任教并参与新文化运动，先后在北京、厦门、广州和上海生活写作。',context:'帝国崩解、启蒙救亡与大众传媒兴起，白话文正在争夺新的公共读者。',style:['冷峻反讽与留白','象征性的心理叙事','杂文的短兵相接'],ideas:['国民性批判','启蒙者的孤独与自省'],works:[{title:'狂人日记',year:'1918',intro:'借被视作疯子的叙述者重读历史，在“吃人”隐喻中质问礼教。'},{title:'阿Q正传',year:'1921—1922',intro:'以不可靠的传记形式揭示精神胜利、权力模仿与革命叙事的裂缝。'}],links:[['caoxueqin','继承并改写小说传统']]},

  {id:'xunzi',subject:'sociology',region:'china',year:-280,dates:'约前 310—前 235',name:'荀子',alias:'礼制社会思想的系统化者',era:'ancient',period:'战国末期',summary:'从欲望、资源、分工与人为规范出发解释群体秩序，把礼看成转化人性、组织社会的制度技术。',life:'赵国人，曾在齐国稷下学宫讲学并任祭酒，后任楚国兰陵令。现存《荀子》由后世编定。',context:'兼并战争加剧，诸子争论如何从分裂中建立可持续的大规模秩序。',style:['层层推进的论辩','譬喻与排比密集','概念兼具伦理与制度意味'],ideas:['化性起伪','礼、分工与群体秩序'],works:[{title:'荀子·性恶',year:'战国',intro:'论证人的自然欲望需要学习、礼义和有意识的努力加以转化。'},{title:'荀子·王制',year:'战国',intro:'从分工、等级和资源治理讨论国家秩序。'}],links:[['confucius','重构儒家礼学'],['shangyang','与法家秩序观对照']]},
  {id:'ibnkhaldun',subject:'sociology',region:'world',year:1377,dates:'1332—1406',name:'伊本·赫勒敦',alias:'历史社会学的先驱',era:'medieval',period:'马格里布—马穆鲁克时代',summary:'用“群体团结”、生计方式和王朝循环解释政治兴衰，把历史材料提升为关于社会机制的比较研究。',life:'生于突尼斯的安达卢西亚裔家族，辗转北非宫廷任职、入狱与出使，后在开罗任教并担任法官。',context:'北非政权频繁更替，游牧与城市社会持续互动，伊斯兰史学已积累大量王朝记录。',style:['从史料批判进入机制解释','类型比较与循环模型','自传经验融入观察'],ideas:['阿萨比亚／群体团结','游牧—城市—王朝循环'],works:[{title:'历史绪论',year:'1377',intro:'为世界史建立方法论导言，讨论社会组织、权力、经济、教育和知识。'}],links:[['braudel','结构史学的远方先声']]},
  {id:'durkheim',subject:'sociology',region:'world',year:1895,dates:'1858—1917',name:'埃米尔·涂尔干',alias:'社会学学科制度的奠基者',era:'modern',period:'法兰西第三共和国',summary:'坚持把社会事实作为独立对象研究，用比较、统计和制度分析解释现代社会的团结与失范。',life:'生于法国犹太家庭，在波尔多和巴黎任教，创办《社会学年鉴》。一战及丧子重创其晚年。',context:'工业化、世俗教育和政治动荡催生了对社会整合的专业研究。',style:['定义先行的严密论证','统计比较与排除法','从制度追问集体表象'],ideas:['社会事实','机械团结与有机团结','失范'],works:[{title:'社会学方法的准则',year:'1895',intro:'说明如何界定、观察并解释社会事实。'},{title:'自杀论',year:'1897',intro:'用群体差异说明看似最私人化的行为也有社会原因。'}],links:[['feixiaotong','学科方法与本土经验']]},
  {id:'feixiaotong',subject:'sociology',region:'china',year:1947,dates:'1910—2005',name:'费孝通',alias:'中国社会学与人类学的本土化者',era:'contemporary',period:'20 世纪中国',summary:'从田野调查出发创造“差序格局”等概念，在社区细节与国家转型之间搭桥。',life:'江苏吴江人，先后求学于燕京、清华和伦敦政治经济学院，师从马林诺夫斯基。长期从事社会调查、教学与公共工作。',context:'乡村危机、战争、国家重建和快速现代化，使“如何认识中国社会”成为持续课题。',style:['从具体社区提炼概念','清楚节制的公共表达','比较而不套用现成模型'],ideas:['差序格局','礼治秩序','从实求知'],works:[{title:'江村经济',year:'1939',intro:'以开弦弓村为个案分析乡村经济、家庭与社会变迁。'},{title:'乡土中国',year:'1947',intro:'以短章概念化熟人社会、差序格局与礼治秩序。'}],links:[['durkheim','从普遍方法到本土概念']]},

  {id:'shangyang',subject:'politics',region:'china',year:-356,dates:'约前 390—前 338',name:'商鞅',alias:'战国国家能力的设计者',era:'ancient',period:'战国 · 秦',summary:'以县制、军功、户籍和法令重组社会资源，把国家富强置于世袭身份与地方传统之上。',life:'卫国人，入秦后受秦孝公重用，主持两次变法。孝公去世后被政敌追究并处死，但制度大体延续。',context:'诸侯战争从贵族竞争转为动员人口、土地和军队的总体竞争。',style:['法令式的明确分类','奖惩对称','以农战衡量政治成效'],ideas:['以法治国与农战','削弱世袭、强化编户齐民'],works:[{title:'商君书',year:'战国—秦汉编成',intro:'商鞅学派文献汇编，围绕法、势、农战和国家动员展开。'}],links:[['xunzi','礼治与法治的张力'],['huangzongxi','强国家与限君权的反题']]},
  {id:'plato',subject:'politics',region:'world',year:-375,dates:'约前 427—前 347',name:'柏拉图',alias:'正义城邦的建构者',era:'ancient',period:'古典希腊',summary:'用对话和思想实验把灵魂秩序、教育与城邦正义连在一起，奠定规范政治哲学的核心问题。',life:'出身雅典贵族家庭，经历伯罗奔尼撒战争与苏格拉底之死，后创办学园并多次前往叙拉古。',context:'雅典民主危机与城邦战争迫使哲学家重新思考知识、德性和统治资格。',style:['戏剧化对话','追问概念定义','寓言与理想模型'],ideas:['正义与灵魂三分','哲人统治与教育'],works:[{title:'理想国',year:'约前 375',intro:'从“正义是否值得”出发，构造城邦、教育、洞穴寓言和哲人王。'}],links:[['rawls','两千年后的正义论重构']]},
  {id:'huangzongxi',subject:'politics',region:'china',year:1663,dates:'1610—1695',name:'黄宗羲',alias:'明清之际的限权思想家',era:'early-modern',period:'明清之际',summary:'从王朝覆亡反思“天下为主、君为客”，主张以学校和公共议论制约一家之法。',life:'浙江余姚人，父亲因东林党争遇害。参与抗清活动后退居著述，讲学并整理明代学术史。',context:'明亡、党争与清初重建，使士人重新追问君主、制度与公共利益。',style:['借三代制度批判现实','史论结合','锋利而克制的制度论证'],ideas:['天下之法','学校作为公共议政空间'],works:[{title:'明夷待访录',year:'1663',intro:'系统批判君主专制，讨论原君、原法、学校与财政兵制。'},{title:'明儒学案',year:'1676 起',intro:'以人物和学派梳理明代思想谱系，是学术史名著。'}],links:[['wangyangming','阳明学的批判继承'],['rawls','公共正义的跨文化对照']]},
  {id:'rawls',subject:'politics',region:'world',year:1971,dates:'1921—2002',name:'约翰·罗尔斯',alias:'当代正义理论的重启者',era:'contemporary',period:'战后美国',summary:'以原初状态和无知之幕重新论证自由平等公民能够接受的制度原则。',life:'美国政治哲学家，经历二战后转向学术，长期任教哈佛大学。其工作推动英美政治哲学从语言分析重新回到规范制度问题。',context:'战后福利国家、民权运动与意识形态竞争让公平分配和基本自由成为制度核心。',style:['思想实验','原则排序','从公平程序推出制度规范'],ideas:['公平的正义','平等自由与差别原则'],works:[{title:'正义论',year:'1971',intro:'通过原初状态论证两项正义原则，并回应功利主义。'},{title:'政治自由主义',year:'1993',intro:'讨论价值多元社会如何形成重叠共识。'}],links:[['plato','延续“何为正义制度”'],['huangzongxi','制度如何服务公共而非私利']]},

  {id:'simaqian',subject:'history',region:'china',year:-91,dates:'约前 145—约前 86',name:'司马迁',alias:'纪传体通史的创造者',era:'ancient',period:'西汉',summary:'让帝王、诸侯、思想家、刺客与普通人的命运并列成史，在事实记录中保留强烈的道德张力与个人目光。',life:'继承父亲司马谈任太史令，遍游各地搜集材料。因替李陵辩护受宫刑，选择忍辱完成《史记》。',context:'汉帝国统一后需要重新组织从传说到当代的共同历史，同时皇权控制历史解释。',style:['本纪、世家、列传互相照见','细节和对话塑造人物','“不虚美、不隐恶”的褒贬'],ideas:['究天人之际','通古今之变','个人命运与制度力量'],works:[{title:'史记',year:'约前 91',intro:'中国第一部纪传体通史，以五种体例组织三千年历史。'}],links:[['herodotus','中西史学的平行起点'],['simaguang','从纪传到编年的再组织']]},
  {id:'herodotus',subject:'history',region:'world',year:-430,dates:'约前 484—前 425',name:'希罗多德',alias:'探究式历史叙事的先驱',era:'ancient',period:'古典希腊',summary:'以旅行见闻、口述传统和因果追问解释希波战争，并保存多民族的风俗与声音。',life:'生于小亚细亚的哈利卡纳苏斯，广泛旅行，晚年可能定居于意大利南部的图里。许多生平细节仍不确定。',context:'希腊城邦与波斯帝国冲突后，跨文化接触促使人们解释战争缘起。',style:['见闻、转述与判断并置','环形插叙','对异域风俗保持好奇'],ideas:['历史作为探究','权力扩张与盛衰反复'],works:[{title:'历史',year:'约前 430',intro:'围绕希波战争展开的九卷叙事，也是民族志、地理志与政治故事的集合。'}],links:[['simaqian','比较：史家如何组织多重声音']]},
  {id:'simaguang',subject:'history',region:'china',year:1084,dates:'1019—1086',name:'司马光',alias:'编年政治史的集大成者',era:'medieval',period:'北宋',summary:'以严格编年和材料考异重构历代治乱，把历史写成统治者判断时势与责任的镜鉴。',life:'北宋政治家、史学家，与王安石政见相左。主持书局十九年编成《资治通鉴》，晚年短暂主持废止新法。',context:'文官政治成熟、印刷和馆阁制度发达，党争使历史经验直接参与现实政治。',style:['逐年推进的因果链','删繁就简而重关键决策','另作考异说明证据取舍'],ideas:['鉴前世之兴衰','政治选择的连续后果'],works:[{title:'资治通鉴',year:'1084',intro:'上起战国、下迄五代的编年体通史，以政治兴衰为主线。'}],links:[['simaqian','改造通史体例'],['braudel','事件史与长时段的张力']]},
  {id:'braudel',subject:'history',region:'world',year:1949,dates:'1902—1985',name:'费尔南·布罗代尔',alias:'长时段史学的代表',era:'contemporary',period:'20 世纪法国',summary:'把地理环境、物质生活和缓慢结构置于事件之前，改变了历史尺度。',life:'法国年鉴学派史家，二战被俘期间凭记忆写作博士论文，战后主持高等研究实践学院并创建人文科学之家。',context:'两次世界大战动摇英雄—事件中心史观，社会科学的结构分析进入历史学。',style:['多层时间尺度','跨区域比较','海洋、气候与物质生活成为主角'],ideas:['长时段','结构—局势—事件'],works:[{title:'地中海与菲利普二世时代的地中海世界',year:'1949',intro:'用三种时间速度重写地中海：地理结构、社会局势与政治事件。'}],links:[['ibnkhaldun','王朝之外的社会机制'],['simaguang','长时段对照编年事件史']]},

  {id:'confucius',subject:'philosophy',region:'china',year:-500,dates:'传统纪年 前 551—前 479',name:'孔子',alias:'以修身重建秩序的教师',era:'ancient',period:'春秋晚期',summary:'从学习、仁、礼和角色实践出发，把哲学做成终身修养与共同生活的艺术。',life:'鲁国人，曾任职并周游列国求仕，晚年返鲁教学。今天的孔子形象主要来自后世编成的《论语》等文献。',context:'周礼秩序衰解，世袭政治松动，游士和私人教育兴起。',style:['短章与情境对话','不把概念封闭定义','以人物行动呈现判断'],ideas:['仁与克己复礼','学而不厌','正名'],works:[{title:'论语',year:'战国前期编定',intro:'弟子及再传弟子记录的言行集，围绕学习、伦理和政治判断展开。'}],links:[['xunzi','儒学中的制度化方向'],['wangyangming','心性实践的再阐释']]},
  {id:'zhuangzi',subject:'philosophy',region:'china',year:-300,dates:'约前 369—前 286',name:'庄子',alias:'以寓言松动边界的思想家',era:'ancient',period:'战国',summary:'用奇异寓言、视角互换和语言悖论，让固化的是非、功用与身份重新流动。',life:'传统称名周，曾任蒙地漆园吏，拒绝楚国聘请。现存《庄子》含庄周本人及后学不同层次作品。',context:'百家争鸣热衷建立普遍秩序，庄子反问任何单一立场的边界和代价。',style:['寓言与怪诞想象','突然换位的视角','悖论、反讽和开放结尾'],ideas:['齐物','逍遥游','无用之用'],works:[{title:'逍遥游',year:'战国',intro:'从鲲鹏变化到小大之辩，追问不依赖外物的自由。'},{title:'齐物论',year:'战国',intro:'通过语言与视角的冲突，松动绝对是非。'}],links:[['wangyangming','主体自由的不同道路']]},
  {id:'wangyangming',subject:'philosophy',region:'china',year:1527,dates:'1472—1529',name:'王阳明',alias:'知行合一的心学家',era:'early-modern',period:'明中期',summary:'把道德根据从外在条目收回主体良知，并要求知识在行动中完成。',life:'浙江余姚人，因反对宦官刘瑾被贬贵州龙场并悟道；后平定叛乱、讲学各地，形成广泛学派。',context:'程朱理学制度化后容易流于章句，商业与地方社会变化也呼唤更主动的道德主体。',style:['从个人困境切入','语录与书信式讲学','概念直接指向行动'],ideas:['心即理','致良知','知行合一'],works:[{title:'传习录',year:'16 世纪编成',intro:'弟子记录的语录、书信和问答，是阳明心学的主要入口。'}],links:[['confucius','重返实践性的儒学'],['huangzongxi','经由明代学脉进入政治反思']]},
  {id:'descartes',subject:'philosophy',region:'world',year:1637,dates:'1596—1650',name:'勒内·笛卡尔',alias:'近代方法论的奠基者',era:'early-modern',period:'17 世纪欧洲',summary:'从方法怀疑和“我思”寻找知识的确定起点，以数学化秩序重建主体与世界。',life:'法国哲学家、数学家，长期居于荷兰写作，晚年受邀赴瑞典宫廷，不久病逝。',context:'宗教冲突、科学革命和经院体系危机推动知识寻找可重复的方法基础。',style:['第一人称的思想自传','分步骤的方法说明','从怀疑推进到演绎'],ideas:['我思故我在','心物二元论','方法怀疑'],works:[{title:'谈谈方法',year:'1637',intro:'以个人求知道路说明四条方法规则，并提出“我思”的确定性。'},{title:'第一哲学沉思集',year:'1641',intro:'通过六个沉思重建自我、上帝和外部世界的知识。'}],links:[['wangyangming','主体作为知识起点的跨文化对照'],['hart','近代分析理性的远源']]},

  {id:'zhangsunwuji',subject:'law',region:'china',year:653,dates:'约 594—659',name:'长孙无忌',alias:'唐律疏议编修代表',era:'medieval',period:'唐初',summary:'主持对律文作官方解释，把刑名、身份、礼制与司法适用组织成高度系统的帝国法典。',life:'唐初政治家，唐太宗长孙皇后之兄，参与玄武门之变并长期居相位；高宗朝因政治斗争被流放后自尽。法典是集体编修成果。',context:'统一帝国需要整合南北朝以来法制，并为各级官僚提供一致的裁判依据。',style:['律文与疏议逐条对应','概念分类严密','以礼制解释法律身份'],ideas:['德礼为政教之本、刑罚为政教之用','法典统一与官僚裁量'],works:[{title:'永徽律疏／唐律疏议',year:'653',intro:'唐律十二篇及官方疏解，深刻影响东亚传统法体系。'}],links:[['shenjiaben','从礼法法典到近代部门法']]},
  {id:'montesquieu',subject:'law',region:'world',year:1748,dates:'1689—1755',name:'孟德斯鸠',alias:'比较法与权力制衡的先驱',era:'early-modern',period:'法国启蒙时代',summary:'不把法律视为孤立命令，而放回政体、气候、经济与风俗的关系网中比较。',life:'法国贵族、法官和思想家，曾游历欧洲并长期观察英国制度。匿名出版《论法的精神》后引发巨大争论。',context:'绝对王权、商业社会和英国宪制经验促使启蒙思想重新解释自由与制度。',style:['跨社会比较','从经验归纳政体原则','大量案例支撑抽象分类'],ideas:['权力制约权力','法律与社会条件的关系'],works:[{title:'论法的精神',year:'1748',intro:'比较政体、法律、风俗和自然条件，提出自由所需的权力安排。'}],links:[['shenjiaben','近代法政知识的输入背景'],['hart','从社会比较到规则分析']]},
  {id:'shenjiaben',subject:'law',region:'china',year:1902,dates:'1840—1913',name:'沈家本',alias:'晚清法律改革主持者',era:'modern',period:'晚清—民初',summary:'在主权危机中主持修律，翻译、比较中外法制，推动传统律例向现代部门法和程序法转型。',life:'浙江归安人，长期任刑部官员，1902 年起与伍廷芳主持修订法律，参与筹建法政教育与大理院制度。',context:'领事裁判权、条约体系与国家转型迫使清廷证明司法的现代性和统一性。',style:['逐条考证旧律','译介与比较并用','改革方案兼顾制度过渡'],ideas:['删除酷刑与刑民分立','以法制现代化收回司法主权'],works:[{title:'寄簃文存',year:'清末民初编',intro:'收录律学考证、修律奏议和法制论说，可见其改革方法。'},{title:'大清新刑律（主持）',year:'1911',intro:'中国首部近代刑法典，虽未充分施行，却标志体例转型。'}],links:[['zhangsunwuji','两种法典化范式'],['montesquieu','比较法与宪政知识输入']]},
  {id:'hart',subject:'law',region:'world',year:1961,dates:'1907—1992',name:'H. L. A. 哈特',alias:'分析法哲学的重建者',era:'contemporary',period:'战后英国',summary:'用初级规则与次级规则的结合解释现代法律体系，并区分法律是什么与法律应当是什么。',life:'英国法哲学家，曾任律师和战时情报人员，后任牛津大学法理学讲席教授，与富勒、德沃金展开重要论争。',context:'战后法治重建和语言哲学推动法学重新分析规则、权威与道德判断。',style:['日常语言分析','用边缘案例检验概念','先描述结构再进行规范评价'],ideas:['承认规则','法律的开放结构','法律与道德的可分离性'],works:[{title:'法律的概念',year:'1961',intro:'以两类规则的结合解释法律体系、义务、裁判和主权。'}],links:[['montesquieu','从制度比较到规则结构'],['shenjiaben','现代法体系的实践与概念两端']]}
]

window.KNOWLEDGE_DATA = { SUBJECTS, PAIRS, BOOKS, ERA_STORIES, AUTHORS }
